#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     star,          tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C2_1,     right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//defining variables. They are all global so that they can be accessed by all of the tasks
bool tophattap = false;
bool tophattap2 = false;
bool startoggle = false;
int gotolevel = 0;
const int level2rot = 7555;
const int level3rot = 14500;
const int level4rot = 23700;
const int maxHeight = 250000;
int lefttemp;
int righttemp;
const int deadband = 10;
bool tempstar = false;
bool tempX = false;
bool toggleX = false;

task changeLift()
{
	while(toggleX)
	{
		if (gotolevel == 0)
		{
			if(nMotorEncoder(lift) == 0)
			{
				motor[lift] = 0;
			}
			else if(nMotorEncoder(lift) > 0)
			{
				motor[lift] = -100;
			}
			else if(nMotorEncoder(lift) < 0)
			{
				motor[lift] = 100;
			}
		}
		else if (gotolevel == 1)
		{
			if(nMotorEncoder(lift) == level2rot)
			{
				motor[lift] = 0;
			}
			else if(nMotorEncoder(lift) > level2rot)
			{
				motor[lift] = -100;
			}
			else if(nMotorEncoder(lift) < level2rot)
			{
				motor[lift] = 100;
			}
		}
		else if(gotolevel == 2)
		{
			if(nMotorEncoder(lift) == level3rot)
			{
				motor[lift] = 0;
			}
			else if(nMotorEncoder(lift) > level3rot)
			{
				motor[lift] = -100;
			}
			else if(nMotorEncoder(lift) < level3rot)
			{
				motor[lift] = 100;
			}
		}
		else if (gotolevel == 3)
		{
			if(nMotorEncoder(lift) == level4rot)
			{
				motor[lift] = 0;
			}
			else if(nMotorEncoder(lift) > level4rot)
			{
				motor[lift] = -100;
			}
			else if(nMotorEncoder(lift) < level4rot)
			{
				motor[lift] = 100;
			}
		}
	}
}

task main()
{

	while(true)
	{
		getJoystickSettings(joystick);

		if(toggleX)
		{
			if(joystick.joy2_TopHat == 0 && tophattap == false && gotolevel != 4)
			{
				gotolevel = gotolevel + 1;
			}
			else if (joystick.joy2_TopHat == 4 && tophattap2 == false && gotolevel != 0)
			{
				gotolevel = gotolevel - 1;
			}
		}
		else
		{
			if (nMotorEncoder(lift) < maxHeight)
			{
			if(joystick.joy2_TopHat == 0)
			{
				motor[lift] = 100;
			}
			else if(joystick.joy2_TopHat == 4)
			{
				motor[lift] = -100;
			}
			else
			{
				motor[lift] = 0;
			}
			}
			else
			{
				motor[lift] = -100;
			}
		}

		if (startoggle)
		{
			motor[star] = - 50;
		}
		else
		{
			if(abs(joystick.joy2_y2) >= deadband)
			{
				motor[star] = joystick.joy2_y2 / 4;
			}
			else
			{
				motor[star] = 0;
			}
		}

		if (joy2Btn(2))
		{
			if (tempstar == false)
			{
				if (startoggle == false)
				{
					startoggle = true;
				}
				else
				{
					startoggle = false;
				}
			}
			tempstar = true;
		}
		else
		{
			tempstar = false;
		}

		lefttemp = (joystick.joy1_y1 / 2) + joystick.joy1_x2;
		righttemp = (joystick.joy1_y1 / 2) - joystick.joy1_x2;
		/*if(joy1Btn(10) == 1)
		{
		righttemp = 400;
		lefttemp = 400;
		fullpower = 1;
		}*/
		motor[left] = lefttemp;
		motor[right] = righttemp;

		if(joy1Btn(2))
		{
			playTone(10, 2);
		}

		/*if(joy1Btn(10) && joy1Btn(11))
		{
		motor[left] = 100;
		motor[right] = 100;
		}*/
		if (joystick.joy2_TopHat == 0)
		{
			tophattap = true;
		}
		else
		{
			tophattap = false;
		}

		if (joystick.joy2_TopHat == 4)
		{
			tophattap2 = true;
		}
		else
		{
			tophattap2 = false;
		}

		if (joy2Btn(2) && tempX == false)
		{
			if (toggleX)
			{
				toggleX = false;
			}
			else
			{
				toggleX = true;
				startTask(changeLift);
			}
		}
		if(joy2Btn(2))
		{
			tempX = true;
		}
		else
		{
			tempX = false;
		}
	}
}
