#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     stars,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//defining variables. They are all global so that they can be accessed by all of the tasks
int fullpower = 0;
bool tophattap = false;
bool tophattap2 = false;
int tophattimer = 0;
int tophattimer2 = 0;
int currentlevel = 1;
int gotolevel = 1;
const int level2rot = 50;
const int level3rot = 100;
const int level4rot = 150;
const int level5rot = 200;
const int deadlift = 25;
int lefttemp;
int righttemp;

//this task is made to change the "currentlevel" to the "gotolevel".
/*task liftuplevel()
{
	//this next if statement is a five-section part, one for each of the levels.
	if(gotolevel == 1)
	{
		while(nMotorEncoder[lift] >= 0)
		{
			motor[lift] = -70; //setting the motor to -70 until it reaches the bottom
		}
		motor[lift] = 0; //stopping the motor
	}
	else if(gotolevel == 2)
	{
		if(currentlevel >= 3) //extra distigtion to tell whether the lift needs to go up or down
		{
			while(nMotorEncoder[lift] >= level2rot) //level#rot holds the encoder value for when the lift is at that level.
			{
				motor[lift] = -70;
			}
		}
		else if(currentlevel <= 1)
		{
			while(nMotorEncoder[lift] <= level2rot)
			{
				motor[lift] = 70;
			}
		}
		motor[lift] = 0;
	}
	else if(gotolevel == 3) //simalar to last "else if"
	{
		if(currentlevel >= 4)
		{
			while(nMotorEncoder[lift] >= level3rot)
			{
				motor[lift] = -70;
			}
		}
		else if(currentlevel <= 5)
		{
			while(nMotorEncoder[lift] <= level3rot)
			{
				motor[lift] = 70;
			}
		}
		motor[lift] = 0;
	}
	else if(gotolevel == 4) //similar to last "else if"
	{
		if(currentlevel >= 5)
		{
			while(nMotorEncoder[lift] >= level4rot)
			{
				motor[lift] = -70;
			}
		}
		else if(currentlevel <= 3)
		{
			while(nMotorEncoder[lift] <= level4rot)
			{
				motor[lift] = 70;
			}
		}
		motor[lift] = 0;
	}
	else if(gotolevel == 5) //reverse of "gotolevel == 1" statement
	{
		while(nMotorEncoder[lift] <= level5rot)
		{
			motor[lift] = 70;
		}
		motor[lift] = 0;
	}
}*/

task main()
{

	while(true)
	{
		getJoystickSettings(joystick);
		/*if(joystick.joy1_TopHat == 0)
		{
			/*tophattap = true;
			/*setting this to true lets us see when it is released,
			if the button isn't pressed and this is true, it was just being pressed
			tophattimer = tophattimer + 1;
			if(tophattimer >= 2000)//once the button has been pressed for long enough for it to cycle 2000 times, it does this
			{
				motor[lift] = 50; //moves the lift up
				tophattap = false; //won't trigger the automatic movement
			}
			else
			{
				tophattap = true; //here because of reasons
				motor[lift] = 0;
			}
		}
		else
		{
			if(tophattap == true) //if the button was just being pressed
			{
				if(currentlevel <= 4) //make sure we aren't going to an invalid level
				{
					gotolevel = currentlevel + 1;
					startTask(liftuplevel);
				}
			}
		}

		if(joystick.joy1_TopHat == 4)
		{
			tophattap2 = true;
			tophattimer2 = tophattimer2 + 1;
			if(tophattimer >= 2000)
			{
				motor[lift] = -50;
				tophattap2 = false;
			}
			else
			{
				tophattap2 = true;
			}
		}
		else
		{
			if(tophattap2 == true)
			{
				if(currentlevel <= 2)
				{
					gotolevel = currentlevel + 1;
					startTask(liftuplevel);
				}
			}
		}
		if(nMotorEncoder[lift] <= deadlift)
		{
			currentlevel = 1;
		}
		else if(abs(level2rot - nMotorEncoder[lift]) <= deadlift)
		{
			currentlevel = 2;
		}
		else if(abs(level3rot - nMotorEncoder[lift]) <= deadlift)
		{
			currentlevel = 3;
		}
		else if(abs(level4rot - nMotorEncoder[lift]) <= deadlift)
		{
			currentlevel = 4;
		}
		else if(abs(level5rot - nMotorEncoder[lift]) <= deadlift)
		{
			currentlevel = 5;
		}*/

		if(joystick.joy1_TopHat == 1)
		{
			motor[lift] = 100;
		}
		else if(joystick.joy1_TopHat == 5)
		{
			motor[lift] = -100;
		}
		else
		{
			motor[lift] = 0;
		}

		lefttemp = joystick.joy1_y1 + joystick.joy1_x2;
		righttemp = joystick.joy1_y1 - joystick.joy1_x2;
		if(joy1Btn(10) == 1)
		{
			righttemp = 400;
			lefttemp = 400;
			fullpower = 1;
		}
		motor[left] = lefttemp / 4;
		motor[right] = righttemp / 4;
	}
}
