#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S3,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     star,          tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C2_1,     right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    grabber,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    incognito,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//defining variables. They are all global so that they can be accessed by all of the tasks
bool tophattap = false;
bool tophattap2 = false;
bool startoggle = false;
int gotolevel = 0;
const int level2rot = 6210;
const int level3rot = 12400;
const int level4rot = 18630;
const int maxHeight = 3000000;
int lefttemp;
int righttemp;
const int deadband = 10;
bool tempstar = false;
bool tempX = false;
bool toggleX = false;
const int liftdeadband = 70;
float grabberPos = 255;

task changeLift()
{
	while(toggleX)
	{
		if (gotolevel == 0)
		{
			if(nMotorEncoder(lift) <= liftdeadband && nMotorEncoder(lift) >= liftdeadband)
			{
				motor[lift] = 0;
			}
			else if(nMotorEncoder(lift) > liftdeadband)
			{
				motor[lift] = -100;
			}
			else if(nMotorEncoder(lift) < -liftdeadband)
			{
				motor[lift] = 100;
			}
		}
		else if (gotolevel == 1)
		{
			if(nMotorEncoder(lift) <= level2rot + liftdeadband && nMotorEncoder(lift) >= level2rot - liftdeadband)
			{
				motor[lift] = 0;
			}
			else if(nMotorEncoder(lift) > level2rot + liftdeadband)
			{
				motor[lift] = -100;
			}
			else if(nMotorEncoder(lift) < level2rot - liftdeadband)
			{
				motor[lift] = 100;
			}
		}
		else if(gotolevel == 2)
		{
			if(nMotorEncoder(lift) <= level3rot + liftdeadband && nMotorEncoder(lift) >= level3rot - liftdeadband)
			{
				motor[lift] = 0;
			}
			else if(nMotorEncoder(lift) > level3rot + liftdeadband)
			{
				motor[lift] = -100;
			}
			else if(nMotorEncoder(lift) < level3rot - liftdeadband)
			{
				motor[lift] = 100;
			}
		}
		else if (gotolevel == 3)
		{
			if(nMotorEncoder(lift) <= level4rot + liftdeadband && nMotorEncoder(lift) >= level4rot - liftdeadband)
			{
				motor[lift] = 0;
			}
			else if(nMotorEncoder(lift) > level4rot + liftdeadband)
			{
				motor[lift] = -100;
			}
			else if(nMotorEncoder(lift) < level4rot - liftdeadband)
			{
				motor[lift] = 100;
			}
		}
	}
}

task main()
{
	int var = maxHeight;
	var = var;
	while(true)
	{
		getJoystickSettings(joystick);

		if(toggleX)
		{
			if(joystick.joy2_TopHat == 0 && tophattap == false && gotolevel != 4)
			{
				gotolevel = gotolevel + 1;
			}
			else if (joystick.joy2_TopHat == 4 && tophattap2 == false && gotolevel != 0)
			{
				gotolevel = gotolevel - 1;
			}
		}
		else
		{
			if(joystick.joy2_TopHat == 0)
			{
				if(!SensorValue(touch))
				{
					motor[lift] = 100;
				}
				else
				{
					motor[lift] = 0;
				}
			}
			else if(joystick.joy2_TopHat == 4)
			{
				motor[lift] = -100;
			}
			else
			{
				motor[lift] = 0;
			}
		}

		if (startoggle)
		{
			motor[star] = - 50;
		}
		else
		{
			if(abs(joystick.joy2_y2) >= deadband)
			{
				motor[star] = joystick.joy2_y2 / 5;
			}
			else
			{
				motor[star] = 0;
			}
		}

		if (joy2Btn(2))
		{
			if (tempstar == false)
			{
				if (startoggle == false)
				{
					startoggle = true;
				}
				else
				{
					startoggle = false;
				}
			}
			tempstar = true;
		}
		else
		{
			tempstar = false;
		}

		if(joy1Btn(5) && joy1Btn(6))
		{
			lefttemp = 100;
			righttemp = 100;
		}
		else if(joy1Btn(7) && joy1Btn(8))
		{
			lefttemp = -100;
			righttemp = -100;
		}
		else
		{
			lefttemp = (joystick.joy1_y1 / 2) + joystick.joy1_x2;
			righttemp = (joystick.joy1_y1 / 2) - joystick.joy1_x2;
		}
		/*if(joy1Btn(10) == 1)
		{
		righttemp = 400;
		lefttemp = 400;
		fullpower = 1;
		}*/
		motor[left] = lefttemp;
		motor[right] = righttemp;

		if(joy1Btn(2))
		{
			playTone(10, 2);
		}

		if (joystick.joy2_TopHat == 0)
		{
			tophattap = true;
		}
		else
		{
			tophattap = false;
		}

		if (joystick.joy2_TopHat == 4)
		{
			tophattap2 = true;
		}
		else
		{
			tophattap2 = false;
		}

		if (joy2Btn(1) && tempX == false)
		{
			if (toggleX)
			{
				toggleX = false;
			}
			else
			{
				toggleX = true;
				startTask(changeLift);
			}
		}
		if(joy2Btn(1))
		{
			tempX = true;
		}
		else
		{
			tempX = false;
		}

		if (joystick.joy1_TopHat == 0 && grabberPos < 200)
		{
			grabberPos = grabberPos + 0.2;
		}
		else if (joystick.joy1_TopHat == 4 && grabberPos > 90)
		{
			grabberPos = grabberPos - 0.2;
		}

		servo[grabber] = grabberPos;
		servo[incognito] = 150;
	}
}
