#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     star,          tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C2_1,     right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int maxHeight = 300000;

task main()
{
	while(true)
	{
		if (SensorValue(IR) == 0)
		{
			//wait10Msec(1);
		}
		else
		{
			//(1);
		}


		while(SensorValue(IR) = 5)
		{
			motor(left) = 50;
			motor(right) = -50;
			wait1Msec(1000);
		}
		while(nMotorEncoder(lift) < maxHeight)
		{
			nMotorEncoder(lift) = 100;
		}

		if(SensorValue(IR) != 4)
		{
			motor(left) = -50;
			motor(right) = 50;
			wait1Msec(1000);
		}
	}
}
