#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     US1,            sensorSONAR)
#pragma config(Sensor, S4,     US2,            sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop, driveRight, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     star,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    leftUS,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    rightUS,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool direction = true;

task main()
{
	while(true)
	{
		if (SensorValue(IR) == 0)
		{
			nxtDisplayTextLine(1, "IR: Not Sensing");
		}
		else
		{
			nxtDisplayTextLine(1, "IR: %d", SensorValue(IR));
		}

		if (SensorValue(US1) == 255)
		{
			nxtDisplayTextLine(2, "USR: Not Sensing");
		}
		else if (SensorValue(US1) == 253 || SensorValue(US1) == 254)
		{
			nxtDisplayTextLine(2, "USR: Not Connected");
		}
		else
		{
			nxtDisplayTextLine(2, "USR: %d", SensorValue(US1));
		}

		if (SensorValue(US2) == 255)
		{
			nxtDisplayTextLine(3, "USL: Not Sensing");
		}
		else if (SensorValue(US2) == 253 || SensorValue(US2) == 254)
		{
			nxtDisplayTextLine(3, "USL: Not Connected");
		}
		else
		{
			nxtDisplayTextLine(3, "USL: %d", SensorValue(US2));
		}

		if (direction == true)
		{
			servo[leftUS] = 255;
			servo[rightUS] = 0;
			if (ServoValue(rightUS) == 255 && ServoValue(leftUS) == 0)
			{
				//direction = false;
			}
		}
		/*else
		{
			servo[leftUS] = 255;
			servo[rightUS] = 0;
			if (ServoValue(rightUS) == 0 && ServoValue(leftUS) == 255)
			{
				direction = true;
			}
		}*/
		nxtDisplayTextLine(5, "S1: %d", ServoValue(rightUS));
		nxtDisplayTextLine(6, "S2: %d", ServoValue(leftUS));
	}
}
