#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S3,     touch,          sensorTouch)
<<<<<<< HEAD
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     star,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     right,         tmotorTetrix, PIDControl, driveRight, encoder)
=======
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     star,          tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C2_1,     right,         tmotorTetrix, openLoop, encoder)
>>>>>>> parent of ebe4e08... PID
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    grabber,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    incognito,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int AutoProg = 0;

task playStarWars()
{
	playTone(695, 14); while(bSoundActive){}
	playTone(695, 14); while(bSoundActive){}
	playTone(695, 14); while(bSoundActive){}
	playTone(929, 83); while(bSoundActive){}
	playTone(1401, 83); while(bSoundActive){}
	playTone(1251, 14); while(bSoundActive){}
	playTone(1188, 14); while(bSoundActive){}
	playTone(1054, 14); while(bSoundActive){}
	playTone(1841, 83); while(bSoundActive){}
	playTone(1401, 41); while(bSoundActive){}
	playTone(1251, 14); while(bSoundActive){}
	playTone(1188, 14); while(bSoundActive){}
	playTone(1054, 14); while(bSoundActive){}
	playTone(1841, 83); while(bSoundActive){}
	playTone(1401, 41); while(bSoundActive){}
	playTone(1251, 14); while(bSoundActive){}
	playTone(1188, 14); while(bSoundActive){}
	playTone(1251, 14); while(bSoundActive){}
	playTone(1054, 55); while(bSoundActive){}
}

task lowerLift()
{
	while(nMotorEncoder(lift) > 5)
	{
		motor[lift] = -100;
		EndTimeSlice();
	}
	motor[lift] = 0;
}

void Auto5()
{
	nMotorEncoder(right) = 0;
	while(nMotorEncoder(right) < 1900)
	{
		motor[left] = -70;
		motor[right] = 70;

	}
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(500);
	nMotorEncoder(left) = 0;
	while(nMotorEncoder(left) < 10)
	{
		motor[left] = 30;
		motor[right] = 30;
	}
	wait1Msec(500);
	nMotorEncoder(right) = 0;
	while(nMotorEncoder(right) > -475)
	{
		motor[left] = 40;
		motor[right] = -40;
	}
	motor[left] = 0;
	motor[right] =0;
	wait1Msec(500);
	nMotorEncoder(lift) = 0;
	//while(nMotorEncoder(lift) <= 26100) //13 and 5 eigths
	while(!SensorValue(touch))
	{
		motor[lift] = 100;
		nxtDisplayTextLine(3, "%d", nMotorEncoder(lift));
	}
	motor[lift] = 0;
	nMotorEncoder(left) = 0;
	while(nMotorEncoder(left) < 400)
	{
		motor[left] = 40;
		motor[right] = 40;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait10Msec(50);
	motor[star] = 50;
	wait10Msec(100);
	motor[star] = 0;
	while(nMotorEncoder(left) > 0)
	{
		motor[left] = -40;
		motor[right] = -40;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(300);
	startTask(lowerLift);
}

void Auto4()
{
	//playTone(5, 500);
	nMotorEncoder(right) = 0;
	while(nMotorEncoder(right) < 2000)
	{
		motor[left] = -60;
		motor[right] = 60;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(500);
	nMotorEncoder(left) = 0;
	while(nMotorEncoder(left) < 500)
	{
		motor[left] = 60;
		motor[right] = 60;
	}
	wait1Msec(500);
	nMotorEncoder(right) = 0;
	while(nMotorEncoder(right) > -1500)
	{
		motor[left] = 50;
		motor[right] = -50;
	}
	motor[left] = 0;
	motor[right] =0;
	wait1Msec(500);
	nMotorEncoder(lift) = 0;
	//while(nMotorEncoder(lift) <= 26000) //13 and 5 eigths
	while(!SensorValue(touch))
	{
		motor[lift] = 100;
		nxtDisplayTextLine(3, "%d", nMotorEncoder(lift));
	}
	motor[lift] = 0;
	nMotorEncoder(left) = 0;
	while(nMotorEncoder(left) < 600)
	{
		motor[left] = 40;
		motor[right] = 40;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait10Msec(50);
	motor[star] = 50;
	wait10Msec(100);
	motor[star] = 0;
	while(nMotorEncoder(left) > 0)
	{
		motor[left] = -30;
		motor[right] = -30;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(300);
	startTask(lowerLift);
}

void Auto0()
{
	nMotorEncoder(right) = 0;
	while(nMotorEncoder(right) < 1800)
	{
		motor[left] = -60;
		motor[right] = 60;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(500);
	nMotorEncoder(left) = 0;
	while(nMotorEncoder(left) < 1300)
	{
		motor[left] = 60;
		motor[right] = 60;
	}
	wait1Msec(500);
	nMotorEncoder(right) = 0;
	while(nMotorEncoder(right) > -2800)
	{
		motor[left] = 50;
		motor[right] = -50;
	}
	motor[left] = 0;
	motor[right] =0;
	wait1Msec(500);
	nMotorEncoder(lift) = 0;
	while(!SensorValue(touch))
	{
		motor[lift] = 100;
		nxtDisplayTextLine(3, "%d", nMotorEncoder(lift));
	}
	motor[lift] = 0;
	nMotorEncoder(left) = 0;
	while(nMotorEncoder(left) < 700)
	{
		motor[left] = 40;
		motor[right] = 40;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait10Msec(50);
	motor[star] = 50;
	wait10Msec(100);
	motor[star] = 0;
	startTask(lowerLift);
	while(nMotorEncoder(left) > 300)
	{
		motor[left] = -40;
		motor[right] = -40;
	}chaj
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(300);
}

	int test1;

task main()
{
	//waitForStart();
	servo[incognito] = 0;
	motor[star] = 20;
	wait1Msec(1000);
	motor[star] = 0;
	nxtDisplayTextLine(1, "%d", nMotorEncoder(right));
	nMotorEncoder(lift) = 0;
<<<<<<< HEAD

	nMotorEncoder[left] = 0;
	nMotorEncoder[right] = 0;

	nMotorEncoderTarget[left] = 3750;
	nMotorEncoderTarget[right] = 3750;

	motor[left] = 40;
	motor[right] = 40;

	while(nMotorRunState(right) != runStateIdle && nMotorRunState(left) != runStateIdle) {test1 = nMotorEncoder(left);}

=======
	while(nMotorEncoder(right) <= 3750)
	{
		motor[left] = 40;
		motor[right] = 40;
	}
>>>>>>> parent of ebe4e08... PID
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(300);
	if(SensorValue(IR) == 6 || SensorValue(IR) == 5)
	{
		AutoProg = 1;
	}
	else if(SensorValue(IR) == 3 || SensorValue(IR) == 2)
	{
		AutoProg = 2;
	}
	else if(SensorValue(IR) == 4)
	{
		AutoProg = 3;
	}
	wait1Msec(300);
	while(nMotorEncoder(right) >= 2675)
	{
		motor[left] = -40;
		motor[right] = -40;
	}
	motor[left] = 0;
	motor[right] = 0;
	nxtDisplayTextLine(1, "%d", nMotorEncoder(right));
	servo[incognito] = 150;
	nxtDisplayTextLine(2, "%d", SensorValue(IR));
	servo[incognito] = 250;
	wait10Msec(100);
	if(AutoProg == 3)
	{
		Auto5();
	}
	else if(AutoProg == 2)
	{
		Auto4();
	}
	else if(AutoProg == 1)
	{
		Auto0();
	}
	startTask(playStarWars);
	nMotorEncoder(left) = 0;
	nMotorEncoder(right) = 0;

	nMotorEncoderTarget[left] = 500;
	nMotorEncoderTarget[right] = -500;

	motor[left] = 60;
	motor[right] = -60;

	while(nMotorRunState[left] != runStateIdle || nMotorRunState[right] != runStateIdle) {}

	motor[left] = 0;
	motor[right] = 0;

	nMotorEncoder(left) = 0;
	nMotorEncoder(right) = 0;

	nMotorEncoderTarget[left] = 600;
	nMotorEncoderTarget[right] = 600;

	motor[left] = 40;
	motor[right] = 40;

	while(nMotorRunState[left] != runStateIdle || nMotorRunState[right] != runStateIdle) {}

	motor[left] = 0;
	motor[right] = 0;

	if(AutoProg == 3)
	{
		nMotorEncoder[left] = 0;
		nMotorEncoder[right] = 0;

		nMotorEncoderTarget[left] = -275;
		nMotorEncoderTarget[right] = 275;

		motor[left] = -40;
		motor[right] = 40;

		while (nMotorRunState[left] != runStateIdle || nMotorRunState[right] != runStateIdle) {}
	}
	else if (AutoProg == 2)
	{
		nMotorEncoder[left] = 0;
		nMotorEncoder[right] = 0;

		nMotorEncoderTarget[left] = -275;
		nMotorEncoderTarget[right] = 275;

		motor[left] = -40;
		motor[right] = 40;

		while (nMotorRunState[left] != runStateIdle || nMotorRunState[right] != runStateIdle) {}
	}
	else if(AutoProg == 1)
	{
		nMotorEncoder[left] = 0;
		nMotorEncoder[right] = 0;

		nMotorEncoderTarget[left] = -275;
		nMotorEncoderTarget[right] = 275;

		motor[left] = -40;
		motor[right] = 40;

		while (nMotorRunState[left] != runStateIdle || nMotorRunState[right] != runStateIdle) {}
	}
	motor[left] = 0;
	motor[right] = 0;
	motor[left] = 100;
	motor[right] = 100;
	wait1Msec(3000);
	motor[left] = 0;
	motor[right] = 0;
	wait10Msec(1000);
}
