#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S3,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     star,          tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C2_1,     right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    grabber,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    incognito,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int AutoProg = 0;

task playStarWars()
{
	playTone(695, 14); while(bSoundActive);
	playTone(695, 14); while(bSoundActive);
	playTone(695, 14); while(bSoundActive);
	playTone(929, 83); while(bSoundActive);
	playTone(1401, 83); while(bSoundActive);
	playTone(1251, 14); while(bSoundActive);
	playTone(1188, 14); while(bSoundActive);
	playTone(1054, 14); while(bSoundActive);
	playTone(1841, 83); while(bSoundActive);
	playTone(1401, 41); while(bSoundActive);
	playTone(1251, 14); while(bSoundActive);
	playTone(1188, 14); while(bSoundActive);
	playTone(1054, 14); while(bSoundActive);
	playTone(1841, 83); while(bSoundActive);
	playTone(1401, 41); while(bSoundActive);
	playTone(1251, 14); while(bSoundActive);
	playTone(1188, 14); while(bSoundActive);
	playTone(1251, 14); while(bSoundActive);
	playTone(1054, 55); while(bSoundActive);
}

task lowerLift()
{
	while(nMotorEncoder(lift) > 5)
	{
		motor[lift] = -100;
		EndTimeSlice();
	}
	motor[lift] = 0;
}

void Auto5()
{
	nMotorEncoder(right) = 0;
	while(nMotorEncoder(right) < 1900)
	{
		motor[left] = -70;
		motor[right] = 70;

	}
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(500);
	nMotorEncoder(left) = 0;
	while(nMotorEncoder(left) < 10)
	{
		motor[left] = 30;
		motor[right] = 30;
	}
	wait1Msec(500);
	nMotorEncoder(right) = 0;
	while(nMotorEncoder(right) > -450)
	{
		motor[left] = 40;
		motor[right] = -40;
	}
	motor[left] = 0;
	motor[right] =0;
	wait1Msec(500);
	nMotorEncoder(lift) = 0;
	//while(nMotorEncoder(lift) <= 26100) //13 and 5 eigths
	while(!SensorValue(touch))
	{
		motor[lift] = 100;
		nxtDisplayTextLine(3, "%d", nMotorEncoder(lift));
	}
	motor[lift] = 0;
	nMotorEncoder(left) = 0;
	while(nMotorEncoder(left) < 375)
	{
		motor[left] = 40;
		motor[right] = 40;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait10Msec(50);
	motor[star] = 50;
	wait10Msec(100);
	motor[star] = 0;
	while(nMotorEncoder(left) > 0)
	{
		motor[left] = -40;
		motor[right] = -40;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(300);
	startTask(lowerLift);
}

void Auto4()
{
	//playTone(5, 500);
	nMotorEncoder(right) = 0;
	while(nMotorEncoder(right) < 2100)
	{
		motor[left] = -60;
		motor[right] = 60;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(500);
	nMotorEncoder(left) = 0;
	while(nMotorEncoder(left) < 550)
	{
		motor[left] = 60;
		motor[right] = 60;
	}
	wait1Msec(500);
	nMotorEncoder(right) = 0;
	while(nMotorEncoder(right) > -1500)
	{
		motor[left] = 50;
		motor[right] = -50;
	}
	motor[left] = 0;
	motor[right] =0;
	wait1Msec(500);
	nMotorEncoder(lift) = 0;
	//while(nMotorEncoder(lift) <= 26000) //13 and 5 eigths
	while(!SensorValue(touch))
	{
		motor[lift] = 100;
		nxtDisplayTextLine(3, "%d", nMotorEncoder(lift));
	}
	motor[lift] = 0;
	nMotorEncoder(left) = 0;
	while(nMotorEncoder(left) < 300)
	{
		motor[left] = 40;
		motor[right] = 40;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait10Msec(50);
	motor[star] = 50;
	wait10Msec(100);
	motor[star] = 0;
	while(nMotorEncoder(left) > 0)
	{
		motor[left] = -40;
		motor[right] = -40;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(300);
	startTask(lowerLift);
}

void Auto0()
{
	nMotorEncoder(right) = 0;
	while(nMotorEncoder(right) < 1800)
	{
		motor[left] = -60;
		motor[right] = 60;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(500);
	nMotorEncoder(left) = 0;
	while(nMotorEncoder(left) < 1300)
	{
		motor[left] = 60;
		motor[right] = 60;
	}
	wait1Msec(500);
	nMotorEncoder(right) = 0;
	while(nMotorEncoder(right) > -2700)
	{
		motor[left] = 50;
		motor[right] = -50;
	}
	motor[left] = 0;
	motor[right] =0;
	wait1Msec(500);
	nMotorEncoder(lift) = 0;
	while(!SensorValue(touch))
	{
		motor[lift] = 100;
		nxtDisplayTextLine(3, "%d", nMotorEncoder(lift));
	}
	motor[lift] = 0;
	nMotorEncoder(left) = 0;
	while(nMotorEncoder(left) < 700)
	{
		motor[left] = 40;
		motor[right] = 40;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait10Msec(50);
	motor[star] = 50;
	wait10Msec(100);
	motor[star] = 0;
	startTask(lowerLift);
	while(nMotorEncoder(left) > 300)
	{
		motor[left] = -40;
		motor[right] = -40;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(300);
}

task main()
{
	waitForStart();
	servo[incognito] = 0;
	motor[star] = 20;
	wait1Msec(1000);
	motor[star] = 0;
	nMotorEncoder(right) = 0;
	nMotorEncoder(lift) = 0;
	nxtDisplayTextLine(1, "%d", nMotorEncoder(right));
	nMotorEncoder(lift) = 0;
	while(nMotorEncoder(right) <= 2700)
	{
		motor[left] = 40;
		motor[right] = 40;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(300);
	if(SensorValue(IR) == 0)
	{
		AutoProg = 1;
	}
	else if(SensorValue(IR) == 4 || SensorValue(IR) == 3)
	{
		AutoProg = 2;
	}
	else if(SensorValue(IR) == 5)
	{
		AutoProg = 3;
	}
	wait1Msec(300);
	while(nMotorEncoder(right) >= 2611)
	{
		motor[left] = -40;
		motor[right] = -40;
	}
	motor[left] = 0;
	motor[right] = 0;
	nxtDisplayTextLine(1, "%d", nMotorEncoder(right));
	servo[incognito] = 150;
	nxtDisplayTextLine(2, "%d", SensorValue(IR));
	servo[incognito] = 250;
	wait10Msec(100);
	if(AutoProg == 3)
	{
		Auto5();
	}
	else if(AutoProg == 2)
	{
		Auto4();
	}
	else if(AutoProg == 1)
	{
		Auto0();
	}
	startTask(playStarWars);
	nMotorEncoder(left) = 0;
	nMotorEncoder(right) = 0;
	while(nMotorEncoder(left) < 500)
	{
		motor[left] = 60;
		motor[right] = -60;
	}
	motor[left] = 0;
	motor[right] = 0;
	nMotorEncoder(left) = 0;
	while(nMotorEncoder(left) < 400)
	{
		motor[left] = 40;
		motor[right] = 40;
	}
	motor[left] = 0;
	motor[right] = 0;
	nMotorEncoder(left) = 0;
	if(AutoProg == 3)
	{
		while(nMotorEncoder(left) > -300)
		{
			motor[left] = -40;
			motor[right] = 40;
		}
	}
	else if (AutoProg == 2)
	{
		while(nMotorEncoder(left) > -325)
		{
			motor[left] = -30;
			motor[right] = 30;
		}
	}
	else if(AutoProg == 1)
	{
		while(nMotorEncoder(left) > -250)
		{
			motor[left] = -40;
			motor[right] = 40;
		}
	}
	motor[left] = 0;
	motor[right] = 0;
	motor[left] = 100;
	motor[right] = 100;
	wait1Msec(3000);
	motor[left] = 0;
	motor[right] = 0;
	wait10Msec(1000);
}
