#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop, driveRight, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     star,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void forwardbackward(int amount, int power, bool forward)
{
	int circumference = 5;
	while (nMotorEncoder(left) <= amount * 360 / circumference)
	{
		if (forward == true)
		{
			motor[left] = power;
			motor[right] = power;
		}
		else
		{
			motor[left] = -power;
			motor[right] = -power;
		}
	}
	motor[left] = 0;
	motor[right] = 0;
}

void turn(int amount, int power, bool leftright)
{
	int circumference = 20;
	int range = 40;
	while (nMotorEncoder(left) <= range * PI / circumference / amount)
	{
		if (leftright)
		{
			motor[left] = power;
			motor[right] = -power;
		}
		else
		{
			motor[left] = -power;
			motor[right] = power;
		}
	}
}

void movelift(int target)
{
	int distanceperrotation = 5;
	int startpos = nMotorEncoder[lift] * distanceperrotation;
	if (target > startpos)
	{
		while(nMotorEncoder(lift) * distanceperrotation < target)
		{
			motor[lift] = 100;
		}
	}
	else if (target < startpos)
	{
		while(nMotorEncoder(lift) * distanceperrotation > target)
		{
			motor[lift] = -100;
		}
	}
	else
	{
		motor[lift] = 0;
	}
	motor[lift] = 0;
}

task main()
{


}
