#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S3,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     star,          tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C2_1,     right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    grabber,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    incognito,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"



int AutoProg = 0;

void Auto5()
{
	nMotorEncoder(right) = 0;
	while(nMotorEncoder(right) < 1900)
	{
		motor[left] = -70;
		motor[right] = 70;

	}
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(500);
	nMotorEncoder(left) = 0;
	while(nMotorEncoder(left) < 25)
	{
		motor[left] = 60;
		motor[right] = 60;
	}
	wait1Msec(500);
	nMotorEncoder(right) = 0;
	while(nMotorEncoder(right) > -400)
	{
		motor[left] = 40;
		motor[right] = -40;
	}
	motor[left] = 0;
	motor[right] =0;
	wait1Msec(500);
	nMotorEncoder(lift) = 0;
	//while(nMotorEncoder(lift) <= 26100) //13 and 5 eigths
	while(!SensorValue (touch))
	{
		motor[lift] = 100;
		nxtDisplayTextLine(3, "%d", nMotorEncoder(lift));
	}
	motor[lift] = 0;
	nMotorEncoder(left) = 0;
	while(nMotorEncoder(left) < 375)
	{
		motor[left] = 40;
		motor[right] = 40;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait10Msec(50);
	motor[star] = 50;
	wait10Msec(100);
	motor[star] = 0;
	while(nMotorEncoder(left) > 0)
	{
		motor[left] = -40;
		motor[right] = -40;
	}
	motor[left] = 0;
	motor[right] = 0;
	wait10Msec(50);
	while(nMotorEncoder(lift) > 15000)
	{
		motor[lift] = -100;
	}
	motor[lift] = 0;

	while(nMotorEncoder(right) > -400)
	{
		motor[left] = -40;
		motor[right] = 40;

	}


	void Auto4()
	{
		nMotorEncoder(right) = 0;
		while(nMotorEncoder(right) < 1500)
		{
			motor[left] = -60;
			motor[right] = 60;
		}
		motor[left] = 0;
		motor[right] = 0;
		wait1Msec(500);
		nMotorEncoder(left) = 0;
		while(nMotorEncoder(left) < 600)
		{
			motor[left] = 60;
			motor[right] = 60;
		}
		wait1Msec(500);
		nMotorEncoder(right) = 0;
		while(nMotorEncoder(right) > -1600)
		{
			motor[left] = 50;
			motor[right] = -50;
		}
		motor[left] = 0;
		motor[right] =0;
		wait1Msec(500);
		nMotorEncoder(lift) = 0;
		//while(nMotorEncoder(lift) <= 26000) //13 and 5 eigths
		while(!SensorValue(touch))
		{
			motor[lift] = 100;
			nxtDisplayTextLine(3, "%d", nMotorEncoder(lift));
		}
		motor[lift] = 0;
		nMotorEncoder(left) = 0;
		while(nMotorEncoder(left) < 300)
		{
			motor[left] = 40;
			motor[right] = 40;
		}
		motor[left] = 0;
		motor[right] = 0;
		wait10Msec(50);
		motor[star] = 50;
		wait10Msec(100);
		motor[star] = 0;
		while(nMotorEncoder(left) > 0)
		{
			motor[left] = -40;
			motor[right] = -40;
		}
		motor[left] = 0;
		motor[right] = 0;
		wait10Msec(300);
		while(nMotorEncoder(lift) > 0)
		{
			motor[lift] = -100;
		}
		motor[lift] = 0;
	}

	void Auto0()
	{
		nMotorEncoder(right) = 0;
		while(nMotorEncoder(right) < 2650)
		{
			motor[left] = -60;
			motor[right] = 60;
		}
		motor[left] = 0;
		motor[right] = 0;
		wait1Msec(500);
		nMotorEncoder(left) = 0;
		while(nMotorEncoder(left) < 1300)
		{
			motor[left] = 60;
			motor[right] = 60;
		}
		wait1Msec(500);
		nMotorEncoder(right) = 0;
		while(nMotorEncoder(right) > -2550)
		{
			motor[left] = 50;
			motor[right] = -50;
		}
		motor[left] = 0;
		motor[right] =0;
		wait1Msec(500);
		nMotorEncoder(lift) = 0;
		//while(nMotorEncoder(lift) <= 26100) //13 and 5 eigths //26100
		while(!SensorValue(touch))
		{
			motor[lift] = 100;
			nxtDisplayTextLine(3, "%d", nMotorEncoder(lift));
		}
		motor[lift] = 0;
		nMotorEncoder(left) = 0;
		while(nMotorEncoder(left) < 425)
		{
			motor[left] = 40;
			motor[right] = 40;
		}
		motor[left] = 0;
		motor[right] = 0;
		wait10Msec(50);
		motor[star] = 50;
		wait10Msec(100);
		motor[star] = 0;
		while(nMotorEncoder(left) > 0)
		{
			motor[left] = -40;
			motor[right] = -40;
		}
		motor[left] = 0;
		motor[right] = 0;
		wait10Msec(300);
		while(nMotorEncoder(lift) > 5)
		{
			motor[lift] = -100;
		}
		motor[lift] = 0;
	}

	task main()
	{
		waitForStart();
		servo[incognito] = 0;
		motor[star] = 20;
		wait1Msec(1000);
		motor[star] = 0;
		nMotorEncoder(right) = 0;
		nMotorEncoder(lift) = 0;
		nxtDisplayTextLine(1, "%d", nMotorEncoder(right));
		nMotorEncoder(lift) = 0;
		while(nMotorEncoder(right) <= 2800)
		{
			motor[left] = 40;
			motor[right] = 40;
		}
		motor[left] = 0;
		motor[right] = 0;
		wait1Msec(300);
		while(nMotorEncoder(right) >= 2611)
		{
			motor[left] = -40;
			motor[right] = -40;
		}
		motor[left] = 0;
		motor[right] = 0;
		nxtDisplayTextLine(1, "%d", nMotorEncoder(right));
		servo[incognito] = 150;
		nxtDisplayTextLine(2, "%d", SensorValue(IR));
		if(SensorValue(IR) == 0)
		{
			AutoProg = 1;
		}
		else if(SensorValue(IR) == 4)
		{
			AutoProg = 2;
		}
		else if(SensorValue(IR) == 5)
		{
			AutoProg = 3;
		}
		servo[incognito] = 250;
		wait10Msec(100);
		if(AutoProg == 3)
		{
			Auto5();
		}
		else if(AutoProg == 2)
		{
			Auto4();
		}
		else if(AutoProg == 1)
		{
			Auto0();
		}
	}
