#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop, driveRight, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     star,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void forwardbackward(int amount, int power, bool forward)
{
	int circumference = 5;
	while (nMotorEncoder(left) <= amount * circumference * 360)
	{
		if (forward == true)
		{
			motor[left] = power;
			motor[right] = power;
		}
		else
		{
			motor[left] = -power;
			motor[right] = -power;
		}
	}
	motor[left] = 0;
	motor[right] = 0;
}

void turn(int amount, int power, int turn, bool leftright)
{
	int circumference = 5;
	while (nMotorEncoder(left) <= amount * circumference * 360)
	{
		if (leftright)
		{
			motor[left] = power + turn;
			motor[right] = power - turn;

		else
		{
			motor[left] = power - turn;
			motor[right] = power + turn;
		}
	}
}

task main()
{
;

}
